import { PROJECT_ENV, PROJECT_ENV_ENUM } from '../constant';

import * as secretBetaConfig from './secret-beta';
import * as secretDevConfig from './secret-dev';
import * as secretProdConfig from './secret-prod';

const JWT_SECRET_MAP = {
  [PROJECT_ENV_ENUM.dev]: secretDevConfig.JWT_SECRET,
  [PROJECT_ENV_ENUM.beta]: secretBetaConfig.JWT_SECRET,
  [PROJECT_ENV_ENUM.prod]: secretProdConfig.JWT_SECRET,
};

const IP_URL_MAP = {
  [PROJECT_ENV_ENUM.dev]: secretDevConfig.IP_URL,
  [PROJECT_ENV_ENUM.beta]: secretBetaConfig.IP_URL,
  [PROJECT_ENV_ENUM.prod]: secretProdConfig.IP_URL,
};

const IP_WHITE_LIST_MAP = {
  [PROJECT_ENV_ENUM.dev]: secretDevConfig.IP_WHITE_LIST,
  [PROJECT_ENV_ENUM.beta]: secretBetaConfig.IP_WHITE_LIST,
  [PROJECT_ENV_ENUM.prod]: secretProdConfig.IP_WHITE_LIST,
};

const QQ_CLIENT_SECRET_MAP = {
  [PROJECT_ENV_ENUM.dev]: secretDevConfig.QQ_CLIENT_SECRET,
  [PROJECT_ENV_ENUM.beta]: secretBetaConfig.QQ_CLIENT_SECRET,
  [PROJECT_ENV_ENUM.prod]: secretProdConfig.QQ_CLIENT_SECRET,
};

const QQ_REDIRECT_URI_MAP = {
  [PROJECT_ENV_ENUM.dev]: secretDevConfig.QQ_REDIRECT_URI,
  [PROJECT_ENV_ENUM.beta]: secretBetaConfig.QQ_REDIRECT_URI,
  [PROJECT_ENV_ENUM.prod]: secretProdConfig.QQ_REDIRECT_URI,
};

const WECHAT_SECRET_MAP = {
  [PROJECT_ENV_ENUM.dev]: secretDevConfig.WECHAT_SECRET,
  [PROJECT_ENV_ENUM.beta]: secretBetaConfig.WECHAT_SECRET,
  [PROJECT_ENV_ENUM.prod]: secretProdConfig.WECHAT_SECRET,
};

const WECHAT_REDIRECT_URI_MAP = {
  [PROJECT_ENV_ENUM.dev]: secretDevConfig.WECHAT_REDIRECT_URI,
  [PROJECT_ENV_ENUM.beta]: secretBetaConfig.WECHAT_REDIRECT_URI,
  [PROJECT_ENV_ENUM.prod]: secretProdConfig.WECHAT_REDIRECT_URI,
};

const QINIU_ACCESSKEY_MAP = {
  [PROJECT_ENV_ENUM.dev]: secretDevConfig.QINIU_ACCESSKEY,
  [PROJECT_ENV_ENUM.beta]: secretBetaConfig.QINIU_ACCESSKEY,
  [PROJECT_ENV_ENUM.prod]: secretProdConfig.QINIU_ACCESSKEY,
};

const QINIU_SECRETKEY_MAP = {
  [PROJECT_ENV_ENUM.dev]: secretDevConfig.QINIU_SECRETKEY,
  [PROJECT_ENV_ENUM.beta]: secretBetaConfig.QINIU_SECRETKEY,
  [PROJECT_ENV_ENUM.prod]: secretProdConfig.QINIU_SECRETKEY,
};

const TENCENTCLOUD_SECRETID_MAP = {
  [PROJECT_ENV_ENUM.dev]: secretDevConfig.TENCENTCLOUD_SECRETID,
  [PROJECT_ENV_ENUM.beta]: secretBetaConfig.TENCENTCLOUD_SECRETID,
  [PROJECT_ENV_ENUM.prod]: secretProdConfig.TENCENTCLOUD_SECRETID,
};

const TENCENTCLOUD_SECRETKEY_MAP = {
  [PROJECT_ENV_ENUM.dev]: secretDevConfig.TENCENTCLOUD_SECRETKEY,
  [PROJECT_ENV_ENUM.beta]: secretBetaConfig.TENCENTCLOUD_SECRETKEY,
  [PROJECT_ENV_ENUM.prod]: secretProdConfig.TENCENTCLOUD_SECRETKEY,
};

const TENCENTCLOUD_CSS_MAP = {
  [PROJECT_ENV_ENUM.dev]: secretDevConfig.TENCENTCLOUD_CSS,
  [PROJECT_ENV_ENUM.beta]: secretBetaConfig.TENCENTCLOUD_CSS,
  [PROJECT_ENV_ENUM.prod]: secretProdConfig.TENCENTCLOUD_CSS,
};

const MYSQL_CONFIG_MAP = {
  [PROJECT_ENV_ENUM.dev]: secretDevConfig.MYSQL_CONFIG,
  [PROJECT_ENV_ENUM.beta]: secretBetaConfig.MYSQL_CONFIG,
  [PROJECT_ENV_ENUM.prod]: secretProdConfig.MYSQL_CONFIG,
};

const REDIS_CONFIG_MAP = {
  [PROJECT_ENV_ENUM.dev]: secretDevConfig.REDIS_CONFIG,
  [PROJECT_ENV_ENUM.beta]: secretBetaConfig.REDIS_CONFIG,
  [PROJECT_ENV_ENUM.prod]: secretProdConfig.REDIS_CONFIG,
};

const SRS_CONFIG_MAP = {
  [PROJECT_ENV_ENUM.dev]: secretDevConfig.SRS_CONFIG,
  [PROJECT_ENV_ENUM.beta]: secretBetaConfig.SRS_CONFIG,
  [PROJECT_ENV_ENUM.prod]: secretProdConfig.SRS_CONFIG,
};

const RABBITMQ_CONFIG_MAP = {
  [PROJECT_ENV_ENUM.dev]: secretDevConfig.RABBITMQ_CONFIG,
  [PROJECT_ENV_ENUM.beta]: secretBetaConfig.RABBITMQ_CONFIG,
  [PROJECT_ENV_ENUM.prod]: secretProdConfig.RABBITMQ_CONFIG,
};

const ALIPAY_LIVE_CONFIG_MAP = {
  [PROJECT_ENV_ENUM.dev]: secretDevConfig.ALIPAY_LIVE_CONFIG,
  [PROJECT_ENV_ENUM.beta]: secretBetaConfig.ALIPAY_LIVE_CONFIG,
  [PROJECT_ENV_ENUM.prod]: secretProdConfig.ALIPAY_LIVE_CONFIG,
};

const SRS_LIVE_MAP = {
  [PROJECT_ENV_ENUM.dev]: secretDevConfig.SRS_LIVE,
  [PROJECT_ENV_ENUM.beta]: secretBetaConfig.SRS_LIVE,
  [PROJECT_ENV_ENUM.prod]: secretProdConfig.SRS_LIVE,
};

const BILIBILI_LIVE_PUSH_KEY_MAP = {
  [PROJECT_ENV_ENUM.dev]: secretDevConfig.BILIBILI_LIVE_PUSH_KEY,
  [PROJECT_ENV_ENUM.beta]: secretBetaConfig.BILIBILI_LIVE_PUSH_KEY,
  [PROJECT_ENV_ENUM.prod]: secretProdConfig.BILIBILI_LIVE_PUSH_KEY,
};

const DOUYU_LIVE_PUSH_KEY_MAP = {
  [PROJECT_ENV_ENUM.dev]: secretDevConfig.DOUYU_LIVE_PUSH_KEY,
  [PROJECT_ENV_ENUM.beta]: secretBetaConfig.DOUYU_LIVE_PUSH_KEY,
  [PROJECT_ENV_ENUM.prod]: secretProdConfig.DOUYU_LIVE_PUSH_KEY,
};

const HUYA_LIVE_PUSH_KEY_MAP = {
  [PROJECT_ENV_ENUM.dev]: secretDevConfig.HUYA_LIVE_PUSH_KEY,
  [PROJECT_ENV_ENUM.beta]: secretBetaConfig.HUYA_LIVE_PUSH_KEY,
  [PROJECT_ENV_ENUM.prod]: secretProdConfig.HUYA_LIVE_PUSH_KEY,
};

export const JWT_SECRET = JWT_SECRET_MAP[PROJECT_ENV];

export const IP_URL = IP_URL_MAP[PROJECT_ENV];

export const IP_WHITE_LIST = IP_WHITE_LIST_MAP[PROJECT_ENV];

export const QQ_CLIENT_SECRET = QQ_CLIENT_SECRET_MAP[PROJECT_ENV];
export const QQ_REDIRECT_URI = QQ_REDIRECT_URI_MAP[PROJECT_ENV];

export const WECHAT_SECRET = WECHAT_SECRET_MAP[PROJECT_ENV];
export const WECHAT_REDIRECT_URI = WECHAT_REDIRECT_URI_MAP[PROJECT_ENV];

export const QINIU_ACCESSKEY = QINIU_ACCESSKEY_MAP[PROJECT_ENV];
export const QINIU_SECRETKEY = QINIU_SECRETKEY_MAP[PROJECT_ENV];

export const TENCENTCLOUD_SECRETID = TENCENTCLOUD_SECRETID_MAP[PROJECT_ENV];
export const TENCENTCLOUD_SECRETKEY = TENCENTCLOUD_SECRETKEY_MAP[PROJECT_ENV];
export const TENCENTCLOUD_CSS = TENCENTCLOUD_CSS_MAP[PROJECT_ENV];

export const MYSQL_CONFIG = MYSQL_CONFIG_MAP[PROJECT_ENV];

export const REDIS_CONFIG = REDIS_CONFIG_MAP[PROJECT_ENV];

export const SRS_CONFIG = SRS_CONFIG_MAP[PROJECT_ENV];

export const RABBITMQ_CONFIG = RABBITMQ_CONFIG_MAP[PROJECT_ENV];

export const ALIPAY_LIVE_CONFIG = ALIPAY_LIVE_CONFIG_MAP[PROJECT_ENV];

export const SRS_LIVE = SRS_LIVE_MAP[PROJECT_ENV];

export const BILIBILI_LIVE_PUSH_KEY = BILIBILI_LIVE_PUSH_KEY_MAP[PROJECT_ENV];

export const DOUYU_LIVE_PUSH_KEY = DOUYU_LIVE_PUSH_KEY_MAP[PROJECT_ENV];

export const HUYA_LIVE_PUSH_KEY = HUYA_LIVE_PUSH_KEY_MAP[PROJECT_ENV];
